_BASE_: "Base-BoxInst-nuscenes.yaml"
MODEL:
  WEIGHTS: '/cpfs2/user/lixiang/.torch/iopath_cache/detectron2/ImageNetPretrained/MSRA/R-101.pkl' #"detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 101
OUTPUT_DIR: "output/boxinst_MS_R_50_1x_nuscenes"
