_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: '/cpfs2/user/lixiang/.torch/iopath_cache/detectron2/ImageNetPretrained/MSRA/R-50.pkl' #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "output/blendmask/R_50_1x"
